services:
  - type: web
    name: framefy
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python framefy.py
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
